---
version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
      - rabbitmq
  mongo:
    image: mongo:7.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb:/Databases/dev.archive
      - mongodb:/Databases/production
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mexpress
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DATABASE_URL}
      ME_CONFIG_MONGODB_SERVER: ${DATABASE_HOST}
      ME_CONFIG_MONGODB_PORT: ${DATABASE_PORT}
    depends_on:
      - mongo
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass

volumes:
  mongodb: {}
  rabbitmq_data: